apiVersion: v2
name: cv
description: Personal CV website
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - cv
  - resume
  - portfolio
maintainers:
  - name: anhnq
    email: anhnq@anhnq.io.vn
