apiVersion: v1
kind: Service
metadata:
  name: cv-site
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: cv-site
  ports:
    - port: {{ .Values.cv.service.port }}
      targetPort: {{ .Values.cv.service.port }}
  type: {{ .Values.cv.service.type }}
